# Generated by Django 4.0.4 on 2022-06-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parroquia',
            old_name='tipo_parroqia',
            new_name='tipo_parroquia',
        ),
        migrations.AlterField(
            model_name='barrio',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_barrios', to='ordenamiento.parroquia'),
        ),
    ]
